### ISSUE TITLE
Jest tests failing

### ISSUE THREAD

**Issue by withrocks** [vim-test/vim-test#505]
Jest tests are failing in 007972e2 with this error:

```
Error detected while processing function test#run[26]..test#execute[18]..test#base#build_args:
line    4:
E118: Too many arguments for function: test#javascript#jest#build_args
E15: Invalid expression: test#{a:runner}#build_args(a:args, !no_color)
Error detected while processing function test#run:
line   26:
E171: Missing :endif
```

Running bisect shows that this was introduced in 19b84e68.

I think I might be able to fix it myself, but want to start by submitting an issue in any case.

**Comment by withrocks** [comment]
Ok, I think I might have an inkling why this happens. The commit that introduced this added this catch to ensure that what I'm experiencing doesn't happen: https://github.com/vim-test/vim-test/blob/19b84e68/autoload/test/base.vim#L38

I guess that this catch doesn't work correctly in NeoVim (which I'm using). I'll look into what needs to happen in that case.

**Comment by withrocks** [comment]
@janko commented in the commit on this behaviour:

```
I didn't find a way in VimScript to check how many arguments a
function supports, so we had to resort to try/catch for backwards
compatibility. We could have updated all runners to accept the second
argument, but that wouldn't solve any custom-made runners that people
might have created locally.
```

I wonder if it would be a good idea to have all runners included in the package support the second argument and also introduce a new function, e.g. called `interface_version` to make dealing with breaking changes easier. If a runner script has that function, it should be called and used to decide which function to call. If it doesn't have, interface_version `1` could be assumed. This could be used for any other function that requires breaking changes too and I believe it might be cleaner (but more code is involved).

The code might look something like this (notice that I'm a vimscript noob):

```
" In base.vim:

" Returns the interface version of the test runner script. If not provided,
" version 1 is assumed. This is so breaking changes can be introduced.
function! test#base#runner_interface_version(runner)
  if exists('g:test#'.a:runner.'interface_version')
    return test#{a:runner}#interface_version()
  else
    return 1
  endif
endfunction

function! test#base#build_args(runner, args, strategy)
  let no_color = has('gui_running') && a:strategy ==# 'basic'
  let interface_version = test#base#runner_interface_version(a:runner)

  if interface_version == 1
    return test#{a:runner}#build_args(a:args)
  else
    return test#{a:runner}#build_args(a:args, !no_color)
  endif
endfunction
```

This way, there would still be an issue if someone has locally implemented a runner script *with* the color argument. But from here on, it would be easier to introduce breaking changes like this.

What do you think?

**Comment by codeinabox** [comment]
I've only skimmed through this issue but my gut feeling is we need to improve our specs to include tests for the no color scenario which would have caught this issue out as the build would have failed. If I have time this weekend I'll add this to all the existing tests and fix those runners that are broken because of it.

**Comment by withrocks** [comment]
I'm pretty sure that it's happening because of that catch I mentioned above is not working as expected in neovim.

I can send in a pull request that I think solves this but would like to get feedback on what maintainers think of having runners supply the version they support (`interface_version`).

**Comment by janko** [comment]
Couldn't we instead update the catch expression to support Neovim?

**Comment by withrocks** [comment]
Sure! That was my first thought also.

But when I saw your reasoning for adding the try/catch (backwards compatibility) I thought that perhaps it would be a good thing to guard against future backwards compatibility issues with versioning. I'm thinking about the next time someone would add a breaking change like this to the api. It means more code, but may make sense in this case because you expect the user to plug-in their own runners.

Let's say someone wants to add a third parameter to that same function. Then this catch would have to support three cases (1, 2 and 3 parameters). It feels a bit cleaner to me to handle those with a version check than with a try/catch. It would for example be simpler to find every case where the API had breaking changes and raise errors if an unsupported version is being used.

Here is a comparison of the two approaches from a reader's perspective:

```
" With try/catch:
function! test#base#build_args(runner, args, strategy)
  let no_color = has('gui_running') && a:strategy ==# 'basic'
  try
    return test#{a:runner}#build_args(a:args, !no_color, third_parameter)
  catch /^Vim\%((\a\+)\)\=:E118/ " too many arguments  " <--- Reader might be confused why we have this catch
  endtry
endfunction

" With versioning
function! test#base#build_args(runner, args, strategy)
  let no_color = has('gui_running') && a:strategy ==# 'basic'
  let interface_version = test#base#runner_interface_version(a:runner)
  if interface_version == 1
    return test#{a:runner}#build_args(a:args)
  elseif interface_version == 2
    return test#{a:runner}#build_args(a:args, !no_color)
  else
     return test#{a:runner}#build_args(a:args, !no_color, third_parameter) " <-- It's clear why this one is being called
  endif
endfunction
```

**Comment by codeinabox** [comment]
I did try a unit test approach but the problem is the tests are run as Vim not Neovim and I can't mock / override `gui_running` in the tests. Could this be fixed just by simplifying the try / catch block to the following? 

```viml
  try
    return test#{a:runner}#build_args(a:args, !no_color)
  catch
    return test#{a:runner}#build_args(a:args)
  endtry
```

**Comment by codeinabox** [comment]
@withrocks I've a created a PR which fixes the issue for me running in Neovim, could you please give it a try

**Comment by janko** [comment]
I think the `interface_version` idea would be an overkill for this problem. Also, it doesn't seem to be specific enough; it's not clear how the numbering should go if other functions change as well, or which numbers are assigned to which functions.

**Comment by codeinabox** [comment]
@withrocks what version of Neovim are you using? I tested the original try / catch logic using Neovim 0.4.3 and it worked fine. I double checked Neovim documentation for try / catch and it does support the patterns we need, for example:

> :catch /^Vim\%((\a\+)\)\=:E123/	" catch error E123

**Comment by withrocks** [comment]
Hi @codeinabox. Good point. I was using NVIM v0.2.2. Just updated my machine and got nvim via `apt` so it was pretty old. Installed the latest beta and it works fine now as far as I can see!

(I guess it might make sense to make it work with the version Ubuntu 18 ships by default, but the issue can be closed as far as I'm concerned.)

@janko That's fair, albeit I was thinking about it to avoid any versioning issue in the future, not specifically to resolve this issue. But regarding your other point about the specificity: I was thinking that it's the version number of all the functions as one set (the whole API). So if any runner function's signature is changed so it breaks compatibility, you would increase the version number.

Thanks for the help!

**Comment by codeinabox** [comment]
Glad to hear upgrading the version of nvim fixed it!

**Comment by AckslD** [comment]
@withrocks @codeinabox I'm getting the same error after simply installing `vim-test` (using `Plug`), setting `test#python#runner = 'pytest'` and running `:TestFile`. I'm using `neovim 0.5.0`.
