### PR TITLE
Simplify catch block in test#base#build_args

### LINKED ISSUE #505: Jest tests failing
Jest tests are failing in 007972e2 with this error:

```
Error detected while processing function test#run[26]..test#execute[18]..test#base#build_args:
line    4:
E118: Too many arguments for function: test#javascript#jest#build_args
E15: Invalid expression: test#{a:runner}#build_args(a:args, !no_color)
Error detected while processing function test#run:
line   26:
E171: Missing :endif
```

Running bisect shows that this was introduced in 19b84e68.

I think I might be able to fix it myself, but want to start by submitting an issue in any case.

### PR DESCRIPTION
**Pull request by codeinabox**
Fixes #505

### CODE REVIEW

**Comment by janko** [comment]
Is there a way to still rescue that particular exception ("too many arguments")? I'm not sure I feel comfortable rescuing *all* exceptions, I think this can make things difficult to debug later on.

**Comment by codeinabox** [comment]
Actually as per comment in the other ticket, the original logic works fine for me so going to close this.
